using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PatientService.Migrations
{
    // ─────────────────────────────────────────────────────────────────────────
    //  InitialCreate — EF Core Migration
    //
    //  This file is AUTO-GENERATED by: dotnet ef migrations add InitialCreate
    //  DO NOT edit by hand — regenerate if you change the model.
    //
    //  Applies:  dotnet ef database update  (or app startup MigrateAsync())
    //  Reverts:  dotnet ef database update 0
    // ─────────────────────────────────────────────────────────────────────────

    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Patients",
                columns: table => new
                {
                    Id          = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    MRN         = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    FullName    = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    DateOfBirth = table.Column<DateTime>(type: "datetime2", nullable: false),
                    BloodGroup  = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: false),
                    Phone       = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    Email       = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    Address     = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    IsDeleted   = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    CreatedAt   = table.Column<DateTime>(type: "datetime2", nullable: false),
                    CreatedBy   = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    UpdatedAt   = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedBy   = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Patients", x => x.Id);
                });

            // Unique index on MRN — no duplicate Medical Record Numbers
            migrationBuilder.CreateIndex(
                name: "IX_Patients_MRN",
                table: "Patients",
                column: "MRN",
                unique: true);

            // Index on Phone — common search field
            migrationBuilder.CreateIndex(
                name: "IX_Patients_Phone",
                table: "Patients",
                column: "Phone");

            // ── Seed 3 demo patients ─────────────────────────────────────────
            migrationBuilder.InsertData(
                table: "Patients",
                columns: new[] { "Id", "MRN", "FullName", "DateOfBirth", "BloodGroup", "Phone", "Email", "Address", "IsDeleted", "CreatedAt", "CreatedBy" },
                values: new object[,]
                {
                    { new Guid("11111111-1111-1111-1111-111111111111"), "MRN-0001", "Ravi Kumar",   new DateTime(1985, 6, 15), "O+", "+91-9876543210", "ravi.kumar@example.com",   "123 MG Road, Mysuru",        false, new DateTime(2025, 1, 1), "seed" },
                    { new Guid("22222222-2222-2222-2222-222222222222"), "MRN-0002", "Priya Sharma",  new DateTime(1992, 3, 22), "B+", "+91-9123456789", "priya.sharma@example.com", "456 Vijayanagar, Mysuru",    false, new DateTime(2025, 1, 1), "seed" },
                    { new Guid("33333333-3333-3333-3333-333333333333"), "MRN-0003", "Anil Patel",    new DateTime(1970, 11, 8), "A-", "+91-9988776655", null,                        "789 Kuvempu Nagar, Mysuru", false, new DateTime(2025, 1, 1), "seed" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "Patients");
        }
    }
}
