// <auto-generated />
// This file is auto-generated by EF Core tools — do not edit manually.
// Regenerated every time you run: dotnet ef migrations add <MigrationName>

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using PatientService.Data;

#nullable disable

namespace PatientService.Migrations
{
    [DbContext(typeof(MediCloudDbContext))]
    partial class MediCloudDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PatientService.Models.Patient", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("MRN").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime>("DateOfBirth").HasColumnType("datetime2");
                b.Property<string>("BloodGroup").IsRequired().HasMaxLength(5).HasColumnType("nvarchar(5)");
                b.Property<string>("Phone").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("Email").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Address").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<bool>("IsDeleted").HasColumnType("bit");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("CreatedBy").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.Property<string>("UpdatedBy").HasMaxLength(100).HasColumnType("nvarchar(100)");

                b.HasKey("Id");
                b.HasIndex("MRN").IsUnique();
                b.HasIndex("Phone");
                b.ToTable("Patients");
            });
#pragma warning restore 612, 618
        }
    }
}
